[platformio]
default_envs = remote_bridge

[env]
platform = espressif32@6.8.1
framework = arduino
monitor_speed = 115200

[env:remote_bridge]
board = esp32dev
build_src_filter = +<remote_bridge/>
lib_deps =
  nrf24/RF24@^1.4.11
  me-no-dev/AsyncTCP@^1.1.4
  ottowinter/ESPAsyncWebServer-esphome@^3.2.2
  bblanchon/ArduinoJson@^7.1.0

[env:boat_receiver]
board = esp32-s3-devkitc-1
build_src_filter = +<boat_receiver/>
lib_deps =
  nrf24/RF24@^1.4.11
  milesburton/DallasTemperature@^4.0.3
  paulstoffregen/OneWire@^2.3.8
  mikalhart/TinyGPSPlus@^1.1.0
  rfetick/MPU6050_light@^1.1.0
